package supermarche

enum class GameState {
    SETUP, PREPARE_PHASE, DELIVERY_PHASE, STOCKING_PHASE,

    // CUSTOMER_PHASE
    RESTOCKING_PHASE, WAITING_FLIP_NEXT, CHOOSE_NEXT_TO_SHOP_OR_RESTOCK,

    OFFER_ITEMS_ON_SALE,

    // SHOPPING_TRIP_PHASE
    WAITING_DICE_ROLL_OR_RESTOCK, DICE_ROLLED, COUPON_BUY, NORMAL_BUY, NORMAL_SALE_BUY, RESTOCKING_PHASE_WHILE_SHOPPING,

    // SHOPPING_TRIP_PHASE_END
    PURCHASE_SUCCESSFUL, PURCHASE_FAILED_NO_STOCK, PURCHASE_FAILED_RESTOCK,

    WASTE_PHASE, GAME_END

}